SELECT AUTHOR.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(PRICE * SALES) as TOTAL_SALES
FROM BOOK
INNER JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
INNER JOIN (
    SELECT *
    FROM BOOK_SALES
    WHERE YEAR(SALES_DATE) = 2022 and MONTH(SALES_DATE) = 1
) AS BOOK_SALES ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
GROUP BY AUTHOR.AUTHOR_ID, AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR.AUTHOR_ID, CATEGORY DESC