select AUTHOR.AUTHOR_ID, AUTHOR_NAME, CATEGORY, sum(SALES*PRICE) as TOTAL_SALES
from BOOK
    join AUTHOR on BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
    join BOOK_SALES on BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
where date_format(BOOK_SALES.SALES_DATE, '%Y-%m') = '2022-01'
group by AUTHOR.AUTHOR_ID, CATEGORY
order by AUTHOR.AUTHOR_ID, CATEGORY desc