SELECT ECOLI_DATA.ID, ifnull(CHILD_COUNT, 0) as CHILD_COUNT
FROM ECOLI_DATA
LEFT JOIN (
    SELECT PARENT_ID, COUNT(*) as CHILD_COUNT
    FROM ECOLI_DATA
    GROUP BY PARENT_ID
) AS PARENT_COUNT ON ECOLI_DATA.ID = PARENT_COUNT.PARENT_ID
ORDER BY ECOLI_DATA.ID