WITH TOTAL_SALE AS (
    SELECT date_format(SALES_DATE, '%Y-%m-%d') as SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    FROM ONLINE_SALE
    WHERE SALES_DATE LIKE '2022-03%'
    
    UNION ALL   -- 중복 제거 안하려면 UNION ALL 사용 권장
    
    SELECT date_format(SALES_DATE, '%Y-%m-%d') as SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
    FROM OFFLINE_SALE
    WHERE SALES_DATE LIKE '2022-03%'
)

SELECT *
FROM TOTAL_SALE
order by SALES_DATE, PRODUCT_ID, USER_ID