select ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.NAME
from ANIMAL_OUTS
inner join ANIMAL_INS on ANIMAL_OUTS.ANIMAL_ID = ANIMAL_INS.ANIMAL_ID
order by datediff(ANIMAL_OUTS.DATETIME, ANIMAL_INS.DATETIME) desc
limit 2