with MAX_INFO as (
    select FOOD_TYPE, max(FAVORITES) as FAVORITES
    from REST_INFO
    group by FOOD_TYPE
)

select REST_INFO.FOOD_TYPE, REST_ID, REST_NAME, REST_INFO.FAVORITES
from REST_INFO
inner join MAX_INFO on MAX_INFO.FOOD_TYPE = REST_INFO.FOOD_TYPE
    and MAX_INFO.FAVORITES = REST_INFO.FAVORITES
order by REST_INFO.FOOD_TYPE desc