select REST_INFO.FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
from REST_INFO
inner join (
    select FOOD_TYPE, max(FAVORITES) as MAX_FAVORITES
    from REST_INFO
    group by FOOD_TYPE
) as MAX_FAVORITES_INFO on REST_INFO.FOOD_TYPE = MAX_FAVORITES_INFO.FOOD_TYPE and REST_INFO.FAVORITES = MAX_FAVORITES_INFO.MAX_FAVORITES
order by REST_INFO.FOOD_TYPE desc