SELECT REST_INFO.FOOD_TYPE, REST_INFO.REST_ID, REST_INFO.REST_NAME, FAVORITES
FROM REST_INFO
INNER JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) AS MAX_INFO ON REST_INFO.FOOD_TYPE = MAX_INFO.FOOD_TYPE and REST_INFO.FAVORITES = MAX_INFO.MAX_FAVORITES
ORDER BY REST_INFO.FOOD_TYPE DESC