SELECT ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.ANIMAL_TYPE, ANIMAL_OUTS.NAME
FROM ANIMAL_OUTS
INNER JOIN (
    SELECT ANIMAL_ID
    FROM ANIMAL_INS
    WHERE SEX_UPON_INTAKE LIKE 'Intact%'
) AS ANIMAL_INS_INFO ON ANIMAL_OUTS.ANIMAL_ID = ANIMAL_INS_INFO.ANIMAL_ID
INNER JOIN (
    SELECT ANIMAL_ID
    FROM ANIMAL_OUTS
    WHERE SEX_UPON_OUTCOME Like 'Spayed%' OR SEX_UPON_OUTCOME Like 'Neutered%'
) AS ANIMAL_OUTS_INFO ON ANIMAL_OUTS.ANIMAL_ID = ANIMAL_OUTS_INFO.ANIMAL_ID
ORDER BY ANIMAL_OUTS.ANIMAL_ID