select REST_INFO.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, round(avg(REVIEW_SCORE), 2) as SCORE
from REST_INFO
join REST_REVIEW on REST_INFO.REST_ID = REST_REVIEW.REST_ID
group by REST_INFO.REST_ID
    having ADDRESS like '서울%'
order by SCORE desc, FAVORITES desc