select YEAR(SALES_DATE) as YEAR, MONTH(SALES_DATE) as MONTH, GENDER, count(distinct(ONLINE_SALE.USER_ID)) as USERS
from ONLINE_SALE
inner join USER_INFO on ONLINE_SALE.USER_ID = USER_INFO.USER_ID
where GENDER is not null
group by YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
order by YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER