with DURATION_INFO as (
    select HISTORY_ID, CAR_ID, START_DATE, END_DATE, datediff(END_DATE, START_DATE)+1 as DURATION
    from CAR_RENTAL_COMPANY_RENTAL_HISTORY
)

select CAR_ID, round(avg(DURATION),1) as AVERAGE_DURATION
from DURATION_INFO
group by CAR_ID
    having round(avg(DURATION),1) >= 7.0
order by AVERAGE_DURATION desc, CAR_ID desc