SELECT DISTINCT CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID,
    CASE
        WHEN RENT_INFO.CAR_ID is null THEN '대여 가능'
        ELSE '대여중'
    END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
LEFT JOIN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE
) AS RENT_INFO ON CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID = RENT_INFO.CAR_ID
ORDER BY CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID DESC