select FOOD_ORDER.PRODUCT_ID, PRODUCT_NAME, sum(AMOUNT)*PRICE as TOTAL_SALES
from FOOD_ORDER
    inner join FOOD_PRODUCT on FOOD_ORDER.PRODUCT_ID = FOOD_PRODUCT.PRODUCT_ID
where year(PRODUCE_DATE)  = 2022 and month(PRODUCE_DATE) = 5
group by FOOD_ORDER.PRODUCT_ID, PRODUCT_NAME
order by TOTAL_SALES desc, FOOD_ORDER.PRODUCT_ID