select FOOD_PRODUCT.PRODUCT_ID, FOOD_PRODUCT.PRODUCT_NAME, sum(PRICE*AMOUNT) as TOTAL_SALES
from FOOD_PRODUCT
inner join FOOD_ORDER
    on FOOD_PRODUCT.PRODUCT_ID = FOOD_ORDER.PRODUCT_ID and year(PRODUCE_DATE) = 2022 and month(PRODUCE_DATE) = 5
group by FOOD_PRODUCT.PRODUCT_ID, FOOD_PRODUCT.PRODUCT_NAME
order by TOTAL_SALES desc, FOOD_PRODUCT.PRODUCT_ID asc