select APNT_NO, PT_NAME, APPOINTMENT.PT_NO, APPOINTMENT.MCDP_CD, DR_NAME, APNT_YMD
from APPOINTMENT
    inner join PATIENT on APPOINTMENT.PT_NO = PATIENT.PT_NO
    inner join DOCTOR on APPOINTMENT.MDDR_ID = DOCTOR.DR_ID
where APNT_YMD like '2022-04-13%' and APNT_CNCL_YN = 'N'
order by APNT_YMD