SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
INNER JOIN (
    SELECT CODE
    FROM SKILLCODES
    WHERE CATEGORY LIKE 'Front%'
) AS FRONTEND_SKILLCODES ON DEVELOPERS.SKILL_CODE & FRONTEND_SKILLCODES.CODE
ORDER BY ID