select USER_ID, NICKNAME, sum(PRICE) as TOTAL_SALES
from USED_GOODS_BOARD
inner join USED_GOODS_USER
    on USED_GOODS_BOARD.WRITER_ID = USED_GOODS_USER.USER_ID
where USED_GOODS_BOARD.STATUS = 'DONE'
group by WRITER_ID
    having sum(PRICE) >= 700000
order by TOTAL_SALES