SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD
INNER JOIN USED_GOODS_USER ON WRITER_ID = USED_GOODS_USER.USER_ID AND STATUS = 'DONE'
GROUP BY USER_ID, NICKNAME HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES