select USER_ID, NICKNAME, sum(PRICE) as TOTAL_SALES
from USED_GOODS_BOARD
join USED_GOODS_USER
    on USED_GOODS_BOARD.WRITER_ID = USED_GOODS_USER.USER_ID
where STATUS = 'DONE'
group by USER_ID, NICKNAME
    having sum(PRICE) >= 500000
order by TOTAL_SALES