SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW
INNER JOIN (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(REVIEW_ID) DESC
    LIMIT 1
) AS MAX_REVIEW_MEMBER ON MAX_REVIEW_MEMBER.MEMBER_ID = REST_REVIEW.MEMBER_ID
INNER JOIN MEMBER_PROFILE ON MEMBER_PROFILE.MEMBER_ID = REST_REVIEW.MEMBER_ID
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC