select SON.ID, SON.GENOTYPE, PARENT.GENOTYPE as PARENT_GENOTYPE
from ECOLI_DATA as SON
    inner join ECOLI_DATA as PARENT on SON.PARENT_ID = PARENT.ID
where SON.GENOTYPE & PARENT.GENOTYPE >= PARENT.GENOTYPE
order by SON.ID