select distinct ID, EMAIL, FIRST_NAME, LAST_NAME
from DEVELOPERS
    inner join SKILLCODES on DEVELOPERS.SKILL_CODE & SKILLCODES.CODE > 0
where SKILLCODES.NAME = 'Python' or SKILLCODES.NAME = 'C#'
order by ID