with YEAR_MAX_SIZE as (
    select year(DIFFERENTIATION_DATE) as YEAR, max(SIZE_OF_COLONY) as MAX_SIZE
    from ECOLI_DATA
    group by year(DIFFERENTIATION_DATE)
)

select YEAR, MAX_SIZE-SIZE_OF_COLONY as YEAR_DEV, ID
from ECOLI_DATA
inner join YEAR_MAX_SIZE on year(ECOLI_DATA.DIFFERENTIATION_DATE) = YEAR_MAX_SIZE.YEAR
order by YEAR, YEAR_DEV