select distinct CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID
from CAR_RENTAL_COMPANY_RENTAL_HISTORY 
inner join CAR_RENTAL_COMPANY_CAR on CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID = CAR_RENTAL_COMPANY_CAR.CAR_ID
where CAR_TYPE = '세단' and year(START_DATE) = 2022 and month(START_DATE) = 10
order by CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID desc