select distinct(CAR_RENTAL_COMPANY_CAR.CAR_ID) as CAR_ID
from CAR_RENTAL_COMPANY_CAR
inner join CAR_RENTAL_COMPANY_RENTAL_HISTORY on CAR_RENTAL_COMPANY_CAR.CAR_ID = CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID
where CAR_TYPE = '세단' and month(START_DATE) = 10
order by CAR_ID desc