SELECT FISH_INFO.ID, FISH_NAME, LENGTH
FROM FISH_INFO
INNER JOIN FISH_NAME_INFO ON FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
INNER JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) AS FISH_MAX_INFO
WHERE FISH_INFO.FISH_TYPE = FISH_MAX_INFO.FISH_TYPE and FISH_INFO.LENGTH = FISH_MAX_INFO.MAX_LENGTH
ORDER BY FISH_INFO.ID