select FISH_INFO.ID, MAX_INFO.FISH_NAME, FISH_INFO.LENGTH
from FISH_INFO
inner join (
    select FISH_NAME, FISH_INFO.FISH_TYPE, max(LENGTH) as LENGTH
    from FISH_INFO
    inner join FISH_NAME_INFO on FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
    group by FISH_NAME, FISH_INFO.FISH_TYPE
) as MAX_INFO on FISH_INFO.FISH_TYPE = MAX_INFO.FISH_TYPE and FISH_INFO.LENGTH = MAX_INFO.LENGTH
order by FISH_INFO.ID