select sum(SCORE) as SCORE, HR_EMPLOYEES.EMP_NO, EMP_NAME, POSITION, EMAIL
from HR_EMPLOYEES
inner join HR_GRADE on HR_EMPLOYEES.emp_no = HR_GRADE.emp_no
group by HR_EMPLOYEES.EMP_NO
order by SCORE DESC
LIMIT 1