SELECT FOOD_PRODUCT.CATEGORY, MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
INNER JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
) AS MAX_INFO ON FOOD_PRODUCT.CATEGORY = MAX_INFO.CATEGORY and FOOD_PRODUCT.PRICE = MAX_INFO.MAX_PRICE
ORDER BY MAX_PRICE DESC